worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80 default_server;
        server_name _;
        location /healthz {
            access_log off;
            return 200 "ok\n";
            add_header Content-Type text/plain;
        }
        location / {
            return 404;
        }
    }

    server {
        listen 80;
        server_name yanyijun.com yijunyan.com;
        location / {
            return 302 https://yyjlincoln.com;
        }
    }

    server {
        listen 80;
        server_name redirect.yyjlincoln.com;
        add_header Access-Control-Allow-Origin *;
        location /resume {
            return 302 https://drive.google.com/file/d/1-SV0MrX_gpyteD2KUiM4WoeSHBEURiZ4/view;
        }
        location /github {
            return 302 https://github.com/yyjlincoln;
        }
        location /linkedin {
            return 302 https://linkedin.com/in/yyjlincoln/;
        }
        location / {
            return 404;
        }
    }

    server {
        listen 80;
        server_name covidwishes.com;
        add_header Access-Control-Allow-Origin *;
        location / {
            return 301 https://yyjlincoln.com/portfolio/wishes;
        }
    }

    server {
        listen 80;
        server_name covidwishes.yyjlincoln.app;
        add_header Access-Control-Allow-Origin *;
        location / {
            return 302 https://yyjlincoln.com/wishes;
        }
    }

    server {
        listen 80;
        server_name vlog.yyjlincoln.com;
        add_header Access-Control-Allow-Origin *;
        location / {
            return 301 https://static.yyjlincoln.com/vlog$request_uri.mov;
        }
    }

    server {
        listen 80;
        server_name documentx.yyjlincoln.app;
        add_header Access-Control-Allow-Origin *;
        location / {
            return 302 https://yyjlincoln.com/documentx;
        }
    }

    server {
        listen 80;
        server_name documentx-ios.yyjlincoln.app;
        add_header Access-Control-Allow-Origin *;
        location / {
            return 302 https://yyjlincoln.com/documentx-ios;
        }
    }

    server {
        listen 80;
        server_name yyjlincoln.app;
        add_header Access-Control-Allow-Origin *;
        location / {
            return 302 https://yyjlincoln.com/portfolio;
        }
    }

    server {
        listen 80;
        server_name docs.yyjlincoln.app;
        add_header Access-Control-Allow-Origin *;
        location / {
            return 302 https://docs.yyjlincoln.com$request_uri;
        }
    }

    server {
        listen 80;
        server_name static.yyjlincoln.app;
        location / {
            return 302 https://static.yyjlincoln.com$uri;
        }
    }

    server {
        listen 80;
        server_name go.mcsrv.icu;
        add_header Access-Control-Allow-Origin *;
        location / {
            return 301 https://hsclinks.yyjlincoln.app$request_uri;
        }
    }

    server {
        listen 80;
        server_name eald.mcsrv.icu;
        add_header Access-Control-Allow-Origin *;
        location / {
            return 301 https://hsceald.yyjlincoln.app$request_uri;
        }
    }

    server {
        listen 80;
        server_name solubility.yyjlincoln.com;
        add_header Access-Control-Allow-Origin *;
        location / {
            return 301 https://hscchem.yyjlincoln.app$request_uri;
        }
    }
}
